document.getElementById('year').textContent = new Date().getFullYear();

const productImages=['product-01.png','product-02.png','product-03.png','product-04.png','product-05.png','product-06.png','product-07.png','product-08.png'];
const productContent={
  en:{names:['Aurora Drop Necklace','Orbit Ring','Lumina Earrings','Infinity Bracelet','Kristi Tiara','Humanoid Circuit Pendant','Chip Core Necklace','Chip Signature Brooch'],descriptions:[
    'A luminous teardrop pendant concept exploring refined symmetry, warm gold architecture and a crystal-like focal form within Kristi’s futuristic visual language.',
    'A sculptural ring concept inspired by orbital movement, combining polished gold geometry with a futuristic sense of balance and motion.',
    'A drop-earring concept built around light, vertical elegance and high-contrast gold detailing for a sleek future-luxury silhouette.',
    'An architectural bracelet concept that translates continuous form and structured gold surfaces into a bold Kristi statement piece.',
    'A ceremonial headpiece concept blending regal jewelry language with futuristic structure, designed as a visual study rather than a finished product.',
    'A youth-oriented pendant concept where electronic circuitry and humanoid form meet gold jewelry language, exploring technology as personal ornament.',
    'A necklace concept built around a recognizable microchip form, reframed with gold contact points and a luxury presentation while preserving its technological identity.',
    'A brooch concept based on the visual language of a microchip, transformed into a distinctive gold statement accessory for a future-facing collection.'
  ]},
  hy:{names:['Ավրորա կաթիլ վզնոց','Ուղեծիր մատանի','Լյումինա ականջօղեր','Անվերջություն ապարանջան','Քրիստի թագ','Մարդակերպ սխեմայի կախազարդ','Չիպի միջուկ վզնոց','Չիպ ստորագրություն բրոշ'],descriptions:[
    'Լուսավոր կաթիլաձև կախազարդի գաղափար՝ նուրբ համաչափությամբ, տաք ոսկեգույն կառուցվածքով և բյուրեղանման կենտրոնական ձևով՝ Քրիստիի ապագայամետ գեղագիտության մեջ։',
    'Քանդակային մատանու գաղափար՝ ոգեշնչված ուղեծրային շարժումից և կառուցված փայլուն ոսկեգույն երկրաչափության, հավասարակշռության ու շարժման զգացողության շուրջ։',
    'Կախվող ականջօղերի գաղափար՝ լույսի, ուղղաձիգ նրբագեղության և արտահայտիչ ոսկեգույն մանրամասների համադրությամբ։',
    'Ճարտարապետական ապարանջանի գաղափար, որտեղ շարունակական ձևն ու կառուցվածքային ոսկեգույն մակերեսները վերածվում են Քրիստիի ընդգծված ոճային շեշտադրության։',
    'Հանդիսավոր գլխազարդի գաղափար՝ թագավորական զարդարվեստի և ապագայամետ կառուցվածքի համադրությամբ՝ որպես ստեղծագործական ուսումնասիրություն, ոչ թե պատրաստի արտադրանք։',
    'Երիտասարդական կախազարդի գաղափար, որտեղ էլեկտրոնային սխեման և մարդակերպ ձևը միանում են ոսկեգույն զարդարվեստին՝ տեխնոլոգիան ներկայացնելով որպես անհատական զարդ։',
    'Վզնոցի գաղափար՝ կառուցված հստակ ճանաչելի միկրոչիպի ձևի շուրջ, ոսկեգույն կոնտակտներով և շքեղ ներկայացմամբ՝ պահպանելով տեխնոլոգիական ինքնությունը։',
    'Բրոշի գաղափար՝ միկրոչիպի տեսողական լեզվի հիմքով, որը վերածված է արտահայտիչ ոսկեգույն աքսեսուարի՝ ապագային ուղղված հավաքածուի համար։'
  ]},
  ar:{names:['عقد قطرة أورورا','خاتم المدار','أقراط لومينا','سوار اللانهاية','تاج كريستي','قلادة الدائرة البشرية','عقد نواة الشريحة','بروش توقيع الشريحة'],descriptions:[
    'تصور لقلادة مضيئة على شكل قطرة، يستكشف التناظر الدقيق والبنية الذهبية الدافئة وشكلاً مركزياً شبيهاً بالكريستال ضمن اللغة المستقبلية لكريستي.',
    'تصور لخاتم نحتي مستوحى من الحركة المدارية، يجمع بين الهندسة الذهبية المصقولة وإحساس مستقبلي بالتوازن والحركة.',
    'تصور لأقراط متدلية يعتمد على الضوء والأناقة العمودية والتفاصيل الذهبية الواضحة لصياغة هيئة فاخرة مستقبلية.',
    'تصور لسوار معماري يحول الشكل المستمر والأسطح الذهبية المنظمة إلى قطعة بارزة تحمل هوية كريستي.',
    'تصور لغطاء رأس احتفالي يمزج لغة المجوهرات الملكية بالبنية المستقبلية، بوصفه دراسة بصرية لا منتجاً نهائياً.',
    'تصور لقلادة شبابية تلتقي فيها الدوائر الإلكترونية بالشكل البشري ولغة المجوهرات الذهبية، لتقديم التكنولوجيا كزينة شخصية.',
    'تصور لعقد مبني حول شكل واضح لشريحة إلكترونية، مع نقاط اتصال ذهبية وعرض فاخر يحافظ على هويته التقنية.',
    'تصور لبروش قائم على اللغة البصرية للشريحة الإلكترونية، محول إلى إكسسوار ذهبي مميز لمجموعة تتجه نحو المستقبل.'
  ]}
};

const en={shopEyebrow:'Concept collection',shopTitle:'Shop Kristi',shopIntro:"These images are visual concept templates that establish Kristi's gold/futuristic design language. They do not represent finished inventory and are not currently offered for sale. Original jewelry photography, final product names, materials and pricing can replace them later without changing the website structure.",aboutEyebrow:'About Kristi',aboutTitle:'Where Heritage Meets the Future',aboutLead:'KRISTI is more than a jewelry brand. It is a creative identity shaped where heritage meets imagination—and where the past begins to speak the language of the future.',aboutP1:'Developed at the intersection of language, art, film, design, and cultural heritage, KRISTI reflects a creative journey that has never belonged to a single discipline.',aboutP2:'Its foundation reaches into philology, linguistics, English literature, and the performing arts, later expanding into the world of visual culture. Work with creative organizations in Armenia—including the Treasures of Armenia Crafts Emporium & Designers’ Guild—deepened this connection to craftsmanship, design, and the enduring artistic traditions of Armenian culture.',aboutP3:'The journey later continued in the United States, bringing together experiences shaped by two worlds and transforming them into a new creative perspective.',aboutP4:'KRISTI Jewelry grows from that intersection: heritage and technology, craftsmanship and imagination, the ancient and the yet-to-come.',aboutP5:'Rather than simply recreating traditional luxury, KRISTI looks toward a new visual language—one in which jewelry can carry memory, identity, technology, and futuristic form.',tagline:'Jewelry from the Future.',behindEyebrow:'Behind Kristi',behindTitle:'Born as Ani Arakelyan in Yerevan, Armenia, Kristi is the creative mind behind the brand.',behindP:'Her journey through language, literature, film, art, cultural heritage, and life between Armenia and the United States ultimately became the foundation for KRISTI—a brand conceived not simply to make jewelry, but to imagine what jewelry can become.',contactEyebrow:'Contact',contactTitle:'Order or ask a question',contactP:'Instagram, WhatsApp and email details will be added here when they are ready.',contactButton:'Contact Kristi',conceptPreview:'Concept Preview',status:'Concept design · Not for sale',view:'View Concept',modalEyebrow:'Kristi Concept Study',modalNotice:'This is a visual design template, not a finished Kristi product and not currently offered for sale. Materials, construction, dimensions, price and final photography will be defined only when an original physical piece is developed.',modalFuture:'Future product page structure: original photography · final materials · dimensions · price · availability · order details.'};

const translations={
  en,
  hy:{...en,shopEyebrow:'Գաղափարային հավաքածու',shopTitle:'Քրիստիի հավաքածու',shopIntro:'Այս պատկերները տեսողական գաղափարային նմուշներ են, որոնք ձևավորում են Քրիստիի ոսկեգույն և ապագայամետ դիզայնի լեզուն։ Դրանք պատրաստի ապրանքներ չեն և այս պահին վաճառքի չեն առաջարկվում։ Հետագայում դրանք կարող են փոխարինվել իրական զարդերի լուսանկարներով, վերջնական անվանումներով, նյութերի նկարագրությամբ և գներով՝ առանց կայքի կառուցվածքը փոխելու։',aboutEyebrow:'Քրիստիի մասին',aboutTitle:'Այնտեղ, որտեղ ժառանգությունը հանդիպում է ապագային',aboutLead:'ՔՐԻՍՏԻ-ն ավելին է, քան զարդերի բրենդը։ Այն ստեղծագործական ինքնություն է՝ ձևավորված այնտեղ, որտեղ ժառանգությունը հանդիպում է երևակայությանը, իսկ անցյալը սկսում է խոսել ապագայի լեզվով։',aboutP1:'Լեզվի, արվեստի, կինոյի, դիզայնի և մշակութային ժառանգության խաչմերուկում ձևավորված ՔՐԻՍՏԻ-ն արտացոլում է ստեղծագործական ճանապարհ, որը երբեք չի սահմանափակվել միայն մեկ ոլորտով։',aboutP2:'Դրա հիմքում լեզվաբանությունն է, բանասիրությունը, անգլիական գրականությունը և կատարողական արվեստը, իսկ հետագայում ճանապարհը բացվել է դեպի տեսողական մշակույթ։ Հայաստանում ստեղծագործական կազմակերպությունների, այդ թվում՝ «Հայաստանի գանձեր» արհեստների կենտրոնի և դիզայներների միության հետ աշխատանքը խորացրել է կապը վարպետության, դիզայնի և հայկական մշակույթի հարատև գեղարվեստական ավանդույթների հետ։',aboutP3:'Հետագայում ճանապարհը շարունակվեց Միացյալ Նահանգներում՝ երկու աշխարհների փորձառությունները միավորելով նոր ստեղծագործական տեսանկյան մեջ։',aboutP4:'ՔՐԻՍՏԻ զարդերը ծնվում են այդ խաչմերուկից՝ ժառանգություն և տեխնոլոգիա, վարպետություն և երևակայություն, հնագույնն ու դեռ չեկածը։',aboutP5:'Ավանդական շքեղությունը պարզապես կրկնելու փոխարեն ՔՐԻՍՏԻ-ն փնտրում է նոր տեսողական լեզու, որտեղ զարդը կարող է կրել հիշողություն, ինքնություն, տեխնոլոգիա և ապագայամետ ձև։',tagline:'Զարդեր ապագայից։',behindEyebrow:'Քրիստիի հետևում',behindTitle:'Երևանում ծնված Անի Առաքելյանը ՔՐԻՍՏԻ բրենդի ստեղծագործական միտքն է։',behindP:'Լեզվի, գրականության, կինոյի, արվեստի և մշակութային ժառանգության միջով անցած նրա ճանապարհը, ինչպես նաև կյանքը Հայաստանի և Միացյալ Նահանգների միջև, դարձան ՔՐԻՍՏԻ-ի հիմքը՝ բրենդի, որը ստեղծվել է ոչ միայն զարդ պատրաստելու, այլ պատկերացնելու համար, թե ինչ կարող է դառնալ զարդը։',contactEyebrow:'Կապ',contactTitle:'Պատվիրել կամ հարց տալ',contactP:'Ինստագրամի, Վոթսափի և էլեկտրոնային փոստի տվյալները կավելացվեն, երբ պատրաստ լինեն։',contactButton:'Կապվել Քրիստիի հետ',conceptPreview:'Գաղափարային նախադիտում',status:'Գաղափարային դիզայն · Չի վաճառվում',view:'Դիտել գաղափարը',modalEyebrow:'Քրիստիի գաղափարային ուսումնասիրություն',modalNotice:'Սա տեսողական դիզայնի գաղափարային նմուշ է, ոչ թե Քրիստիի պատրաստի արտադրանք, և այս պահին վաճառքի չի առաջարկվում։ Նյութերը, կառուցվածքը, չափերը, գինը և վերջնական լուսանկարները կորոշվեն միայն այն ժամանակ, երբ ստեղծվի իրական ֆիզիկական զարդը։',modalFuture:'Ապագա ապրանքի էջի կառուցվածքը՝ իրական լուսանկարներ · վերջնական նյութեր · չափեր · գին · հասանելիություն · պատվերի տվյալներ։'},
  ar:{...en,shopEyebrow:'مجموعة تصورية',shopTitle:'مجموعة كريستي',shopIntro:'هذه الصور نماذج بصرية تصورية ترسم لغة كريستي الذهبية والمستقبلية في التصميم. وهي لا تمثل منتجات نهائية ولا تُعرض للبيع حالياً. ويمكن لاحقاً استبدالها بصور المجوهرات الأصلية والأسماء النهائية والمواد والأسعار من دون تغيير بنية الموقع.',aboutEyebrow:'عن كريستي',aboutTitle:'حيث يلتقي التراث بالمستقبل',aboutLead:'كريستي أكثر من علامة مجوهرات؛ إنها هوية إبداعية تتشكل حيث يلتقي التراث بالخيال وحيث يبدأ الماضي في التحدث بلغة المستقبل.',aboutP1:'تطورت كريستي عند تقاطع اللغة والفن والسينما والتصميم والتراث الثقافي، وتعكس رحلة إبداعية لم تنتمِ يوماً إلى مجال واحد فقط.',aboutP2:'تمتد جذورها إلى فقه اللغة واللسانيات والأدب الإنجليزي والفنون الأدائية، ثم توسعت لاحقاً إلى عالم الثقافة البصرية. وقد عمّق العمل مع مؤسسات إبداعية في أرمينيا، ومنها مركز «كنوز أرمينيا» للحِرف ورابطة المصممين، الصلة بالحرفية والتصميم والتقاليد الفنية الراسخة للثقافة الأرمنية.',aboutP3:'استمرت الرحلة لاحقاً في الولايات المتحدة، جامعةً خبرات عالمين في رؤية إبداعية جديدة.',aboutP4:'تنمو مجوهرات كريستي من هذا التقاطع: التراث والتكنولوجيا، الحرفية والخيال، القديم وما لم يأتِ بعد.',aboutP5:'بدلاً من إعادة إنتاج الفخامة التقليدية، تتطلع كريستي إلى لغة بصرية جديدة يمكن فيها للمجوهرات أن تحمل الذاكرة والهوية والتكنولوجيا والشكل المستقبلي.',tagline:'مجوهرات من المستقبل.',behindEyebrow:'خلف كريستي',behindTitle:'وُلدت آني أراكيليان في يريفان، أرمينيا، وهي العقل الإبداعي وراء علامة كريستي.',behindP:'رحلتها عبر اللغة والأدب والسينما والفن والتراث الثقافي، وحياتها بين أرمينيا والولايات المتحدة، أصبحت الأساس لكريستي؛ علامة لم تُبتكر لمجرد صنع المجوهرات، بل لتخيل ما يمكن أن تصبح عليه المجوهرات.',contactEyebrow:'اتصال',contactTitle:'اطلب أو اطرح سؤالاً',contactP:'ستُضاف بيانات إنستغرام وواتساب والبريد الإلكتروني عندما تصبح جاهزة.',contactButton:'تواصل مع كريستي',conceptPreview:'معاينة تصورية',status:'تصميم تصوري · غير معروض للبيع',view:'عرض التصور',modalEyebrow:'دراسة كريستي التصورية',modalNotice:'هذا نموذج بصري تصوري للتصميم، وليس منتجاً نهائياً من كريستي، ولا يُعرض للبيع حالياً. ستُحدد المواد والبنية والأبعاد والسعر والصور النهائية فقط عند تطوير قطعة فعلية أصلية.',modalFuture:'هيكل صفحة المنتج مستقبلاً: صور أصلية · مواد نهائية · أبعاد · سعر · توافر · تفاصيل الطلب.'},
  zh:{...en,shopEyebrow:'概念系列',shopTitle:'选购 Kristi',shopIntro:'这些图像是用于建立 Kristi 金色未来主义设计语言的视觉概念模板，并非成品库存，目前不对外销售。'},
  de:{...en,shopEyebrow:'Konzeptkollektion',shopTitle:'Kristi entdecken'},
  hi:{...en,shopEyebrow:'कॉन्सेप्ट कलेक्शन',shopTitle:'Kristi देखें'},
  fa:{...en,shopEyebrow:'مجموعه مفهومی',shopTitle:'مشاهده Kristi'},
  ru:{...en,shopEyebrow:'Концептуальная коллекция',shopTitle:'Коллекция Kristi'},
  es:{...en,shopEyebrow:'Colección conceptual',shopTitle:'Descubre Kristi'},
  tr:{...en,shopEyebrow:'Konsept koleksiyonu',shopTitle:'Kristi’yi Keşfet'}
};

const productGrid=document.getElementById('productGrid');
const modal=document.getElementById('conceptModal');
const modalImage=document.getElementById('conceptImage');
const modalTitle=document.getElementById('conceptTitle');
const modalDescription=document.getElementById('conceptDescription');
let currentLanguage='en';

function localizedProducts(){return productContent[currentLanguage]||productContent.en;}
function renderProducts(){const t=translations[currentLanguage]||en;const pc=localizedProducts();productGrid.innerHTML=productImages.map((img,i)=>`<article class="product-card" data-product="${i}"><span class="concept-badge">${t.conceptPreview}</span><img class="product-image" src="${img}" alt="${pc.names[i]}"><h2>${pc.names[i]}</h2><p class="product-status">${t.status}</p><button class="text-button concept-button" type="button">${t.view}</button></article>`).join('');document.querySelectorAll('.concept-button').forEach(b=>b.addEventListener('click',()=>openConcept(Number(b.closest('.product-card').dataset.product))));}
function applyLanguage(code){currentLanguage=translations[code]?code:'en';const t=translations[currentLanguage];document.documentElement.lang=currentLanguage;document.documentElement.dir=['ar','fa'].includes(currentLanguage)?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(t[key])el.textContent=t[key];});renderProducts();localStorage.setItem('kristiLanguage',currentLanguage);}
function openConcept(index){const pc=localizedProducts();if(!modal)return;modalImage.src=productImages[index];modalImage.alt=pc.names[index];modalTitle.textContent=pc.names[index];modalDescription.textContent=pc.descriptions[index]||productContent.en.descriptions[index];modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}
function closeConcept(){if(!modal)return;modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}
document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',closeConcept));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal?.classList.contains('is-open'))closeConcept();});
const selector=document.getElementById('languageSelect');
const saved=localStorage.getItem('kristiLanguage')||'en';selector.value=saved;selector.addEventListener('change',e=>applyLanguage(e.target.value));applyLanguage(saved);
